FROM openjdk:8-jdk-alpine
WORKDIR /app
COPY /target/presence-detector-1.0.0-SNAPSHOT.jar ./app.jar

RUN addgroup -g 1000 -S moduleuser && \
    adduser -u 1000 -S moduleuser -G moduleuser

USER moduleuser

ENTRYPOINT ["java","-jar","./app.jar"]