FROM openjdk:8-jdk-alpine

WORKDIR /app
COPY /target/watcher-1.0.0-SNAPSHOT.jar ./app.jar

RUN addgroup -g 1000 -S moduleuser && \
    adduser -u 1000 -S moduleuser -G moduleuser

RUN mkdir /images
RUN mkdir /models
RUN mkdir /models/trained_model

COPY trained_model /models/trained_model

USER moduleuser
EXPOSE 5005/tcp

ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n","-jar","./app.jar"]