FROM openjdk:8-jdk-alpine
WORKDIR /app
COPY /target/presenceDetector-1.0.0-SNAPSHOT.jar ./app.jar

RUN addgroup -g 1000 -S moduleuser && \
    adduser -u 1000 -S moduleuser -G moduleuser

USER moduleuser
EXPOSE 5005/tcp

ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n","-jar","./app.jar"]